from django.urls import path
from.import views

urlpatterns = [
    path('ratedoctor/',views.ratedoctor,name='ratedoctor'),
    path('reportdoctor/',views.reportdoctor,name='reportdoctor'),
    path('admindashboard/',views.admindashboard,name='admindashboard'),
    path('adminpanel/',views.adminpanel,name='adminpanel'),
    path('patientverification/',views.patientverification,name='patientverification'),
    path('doctorverification/',views.doctorverification,name='doctorverification'),
    path('patientpersonaldetails/',views.patientpersonaldetails,name='patientpersonaldetails'),
    path('doctorpersonaldetails/',views.doctorpersonaldetails,name='doctorpersonaldetails'),
    path('blogs/',views.blogs,name='blogs'),
    path('blog1/',views.blog1,name='blog1'),
    path('blog2/',views.blog2,name='blog2'),
    path('blog3/',views.blog3,name='blog3'),
    path('blog4/',views.blog4,name='blog4'),
    path('blog5/',views.blog5,name='blog5'),
    path('videocall/',views.videocall,name='videocall'),
    path('reporthistorypage/',views.reporthistorypage,name='reporthistorypage'),
    path('createpatientreport/',views.createpatientreport,name='createpatientreport'),
    path('',views.index,name='index'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('doctors/', views.doctors, name='doctors'),
    path('departments/', views.departments, name='departments'),
    path('doctorlogin/', views.doctorlogin, name='doctorlogin'),
    path('doctorsignup/', views.doctorsignup, name='doctorsignup'),
    path('patientlogin/', views.patientlogin, name='patientlogin'),
    path('patientsignup/', views.patientsignup, name='patientsignup'),
    path('doctordashboard/', views.doctordashboard, name='doctordashboard'),
    path('patientdashboard/', views.patientdashboard, name='patientdashboard'),
    path('viewbookingstatus/', views.viewbookingstatus, name='viewbookingstatus'),
    path('bookingpanel/', views.bookingpanel, name='bookingpanel'),
]